# Generated by Django 5.2.8 on 2025-11-24 15:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('prompt_description', models.TextField(blank=True, null=True)),
                ('prompt_text', models.TextField()),
                ('guidance', models.TextField(blank=True, null=True)),
                ('task_type', models.CharField(choices=[('create_content', 'Create Content'), ('create_code', 'Create Code'), ('research', 'Research'), ('deep_research', 'Deep Research / Analysis'), ('plan_organize', 'Plan & Organize'), ('ideate', 'Ideate / Brainstorm'), ('summarize', 'Summarize / Review'), ('explain', 'Explain / Teach'), ('optimize', 'Optimize / Improve')], max_length=50)),
                ('output_format', models.CharField(choices=[('text', 'Text'), ('code', 'Code'), ('chart_graph', 'Chart / Graph'), ('checklist_table', 'Checklist / Table'), ('template_framework', 'Template / Framework'), ('image_visual', 'Image / Visual'), ('slide_report', 'Slide / Report')], max_length=50)),
                ('category', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20)),
                ('vote', models.IntegerField(default=0)),
                ('like_count', models.IntegerField(default=0)),
                ('dislike_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prompts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PromptVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_created_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=255)),
                ('prompt_description', models.TextField(blank=True, null=True)),
                ('prompt_text', models.TextField()),
                ('guidance', models.TextField(blank=True, null=True)),
                ('task_type', models.CharField(choices=[('create_content', 'Create Content'), ('create_code', 'Create Code'), ('research', 'Research'), ('deep_research', 'Deep Research / Analysis'), ('plan_organize', 'Plan & Organize'), ('ideate', 'Ideate / Brainstorm'), ('summarize', 'Summarize / Review'), ('explain', 'Explain / Teach'), ('optimize', 'Optimize / Improve')], max_length=50)),
                ('output_format', models.CharField(choices=[('text', 'Text'), ('code', 'Code'), ('chart_graph', 'Chart / Graph'), ('checklist_table', 'Checklist / Table'), ('template_framework', 'Template / Framework'), ('image_visual', 'Image / Visual'), ('slide_report', 'Slide / Report')], max_length=50)),
                ('category', models.CharField(max_length=50)),
                ('edited_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('prompt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='api.prompt')),
            ],
            options={
                'ordering': ['-version_created_at'],
            },
        ),
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to=settings.AUTH_USER_MODEL)),
                ('prompt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='api.prompt')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'prompt'), name='unique_user_prompt_bookmark')],
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.SmallIntegerField(choices=[(1, 'Upvote'), (-1, 'Downvote')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('prompt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='api.prompt')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'prompt'), name='unique_user_prompt_vote')],
            },
        ),
    ]
