# Generated by Django 5.2.8 on 2025-11-26 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prompt',
            name='copy_count',
            field=models.IntegerField(default=0),
        ),
    ]
