# Generated by Django 5.2.8 on 2025-11-28 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_copiedpromptfeedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prompt',
            name='output_format',
            field=models.CharField(blank=True, choices=[('text', 'Text'), ('code', 'Code'), ('chart_graph', 'Chart / Graph'), ('checklist_table', 'Checklist / Table'), ('template_framework', 'Template / Framework'), ('image_visual', 'Image / Visual'), ('slide_report', 'Slide / Report')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='prompt',
            name='task_type',
            field=models.CharField(blank=True, choices=[('create_content', 'Create Content'), ('create_code', 'Create Code'), ('research', 'Research'), ('deep_research', 'Deep Research / Analysis'), ('plan_organize', 'Plan & Organize'), ('ideate', 'Ideate / Brainstorm'), ('summarize', 'Summarize / Review'), ('explain', 'Explain / Teach'), ('optimize', 'Optimize / Improve')], max_length=50, null=True),
        ),
    ]
