# Generated by Django 5.2.8 on 2025-11-28 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_prompt_output_format_alter_prompt_task_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='copiedpromptfeedback',
            name='rating',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='copiedpromptfeedback',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('submitted', 'Submitted'), ('skipped', 'Skipped')], default='pending', max_length=20),
        ),
    ]
